development:
  forest_env_secret: 771b1f63d48ae780f11c3f84cbeb085a7df894ce72ce701b844a6c56758da95d
  forest_auth_secret: QWMkfrSVTENAVa-ToHSHNg
staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
